### ISSUE TITLE
haijin_kabe/lib/chwall.sh should be executable

### ISSUE THREAD

**Issue by syhily** [TimWei/haijin_kabe#6]

**Comment by TimWei** [comment]
Although its not in my plan to let user running it standalone.
I think its okay to adding it.
thanks for suggestion.

**Comment by TimWei** [comment]
done at [814053300152b69097edd8a226f676bfbdf8a9cd](https://github.com/TimWei/haijin_kabe/commit/814053300152b69097edd8a226f676bfbdf8a9cd)

plz contact me with issues if there is anything broken lulz.
and all suggestions will be welcome.
