### ISSUE TITLE
Make the wallpaper update frequency configurable

### ISSUE THREAD

**Issue by syhily** [TimWei/haijin_kabe#7]

**Comment by TimWei** [comment]
Sure, I'll add it into config/kabe_setting.yaml.
thanks for suggestion.

**Comment by TimWei** [comment]
done at [72b03e9111eca7b278457694452aee78214f7f00](https://github.com/TimWei/haijin_kabe/commit/72b03e9111eca7b278457694452aee78214f7f00)

feel free to contact me with create another issue if there is any problems.
