### ISSUE TITLE
Pixiv has abadoned the old public API

### ISSUE THREAD

**Issue by kokororin** [TimWei/haijin_kabe#8]
Some image urls are broken.
Here's the new API.

`https://api.pixiv.moe/v2/ranking`
`https://api.pixiv.moe/v2/ranking?page=2`

**Comment by TimWei** [comment]
thanks, will fix it later.

**Comment by TimWei** [comment]
fixed @ [#e82fc7c](https://github.com/TimWei/haijin_kabe/commit/44757f259dfda370b0e9b04c4bc69035ccb4d0dd)
